### PR TITLE
Rel5 bzkf additions

### PR DESCRIPTION
**Pull request by BoehmDo**
[Matching Fhirspark Pullrequest: ](https://github.com/nr23730/fhirspark/pull/389)

Adds a new annotation in the patientview mutation-tables. This annotates given alterations with previously documented therapy-recommendations from the local fhir-server as well as a potential external data source for shared data. Also includes additions to the Therapyrecommendation data-model to enable this feature. Unfortunately touches a lot of files, which is necessary to deliver Data to the relevant front-end components.

## Any screenshots or GIFs?
annotation_local_focused

### CODE REVIEW

**Review by nr23730 — CHANGES_REQUESTED** [review]
Hi @BoehmDo, thank you very much for this contribution!

In general, this looks very good and works quite nice. By now I changed one minor thing, after discussing this in the cBioPortal Slack: The *old* OncoKB URL that was HTTPS encrypted (https://oncokb.mskcc.org) is not available anymore. Instead https://oncokb.info should be used. Otherwise cBioPortal would not load in the dev environment, where this is being called directly.

One thing that I noticed was that when clicking things in the Shared Recommendation Tab was that it also did things with the integrated IGV viewer. That is a bit confusing.

**Comment by BoehmDo** [comment]
Hi @nr23730, thank you for your feedback and the fixed URL!
Just for clarification, are you referring to the changing alteration in the IGV-viewer, or are you able to interact with the IGV-viewer through the loaded tooltip? In case of the former, that would be default behaviour for all annotations in the mutation-tables, including oncokb and civic. It seems like it is always tracking the currently focused Table-Row, which changes when first clicking on one of the tooltips.

**Comment by nr23730** [comment]
Okay, so than it's more like a general issue that should be resolved upstream. 
Then this is an approval from my side. For the other PR I will need some time.

**Review by nr23730 — APPROVED** [review]

**Comment by nr23730** [comment]
superseeded by #95

**Pull request closed without merging**
