### PR TITLE
Add icon with tooltip showing author of therapy recommendation and mtb

### LINKED ISSUE #24: Display who created a therapy recommendation.
We should display the creators of therapy recommendations. As entries are freely editable we should also show users who edited therapy recommendations.
One option would be a mouse-over info icon in the 'Edit' column.

### PR DESCRIPTION
**Pull request by Unberath**
Closes #24 

Describe changes proposed in this pull request:
- Added icon with tooltip showing author (or alternative message on portals without login) for therapy recommendation
- Added icon with tooltip showing author (or alternative message on portals without login) for mtb

### CODE REVIEW

**Review by nr23730 — COMMENTED** [review]
Code-wise this looks good! I don't know if the end users will like tooltip. This should be evaluated.
In my opiniom it would make sense to also include date and time of last modification.

**Comment by Unberath** [comment]
> Code-wise this looks good! I don't know if the end users will like tooltip. This should be evaluated.

You're right, this should be evaluated. My thought process was that the author is just not important enough to be displayed all the time.

> In my opiniom it would make sense to also include date and time of last modification.

Are we still able to do that? Commit nr23730/cbioportal-frontend@d85952f removed the modification list in favor of the author string.

**Comment by nr23730** [comment]
> You're right, this should be evaluated. My thought process was that the author is just not important enough to be displayed all the time.

Okay, then for now I'm fine with that!

> Are we still able to do that? Commit [d85952f](https://github.com/nr23730/cbioportal-frontend/commit/d85952f) removed the modification list in favor of the author string.

Good point! My fault, I'll fix this. For now it would suggest that we also integrate this into the tooltip?

**Review by nr23730 — APPROVED** [review]

**Comment by Unberath** [comment]
> Good point! My fault, I'll fix this. For now it would suggest that we also integrate this into the tooltip?

If we have the information about modifications we should definitely add it into the tooltip!

**Pull request merged**
