### PR TITLE
Improve display of MTB Info

### LINKED ISSUE #45: Presentation of MTB info is ambigous
- Delete button of MTB looks the same as delete button of therapy recommendations
- Date and state field don't have a label

### PR DESCRIPTION
**Pull request by Unberath**
Fix nr23730/cbioportal-frontend#45

Changes
- Rename delete MTB button to 'Delete MTB'
- Add labels for MTB date and state

### CODE REVIEW

**Review by nr23730 — APPROVED** [review]
lgtm!

**Comment by nr23730** [comment]
I did a quick merge of 3.6.6 to resolve the conflicts.

**Comment by Unberath** [comment]
Do you have the same issue with the preceding `0` @nr23730 ?
image

**Comment by nr23730** [comment]
> Do you have the same issue with the preceding `0` @nr23730 ?
> image

Fixed that!

**Comment by Unberath** [comment]
> Fixed that!

Perfect, thank you!

**Pull request merged**
