### PR TITLE
Therapy recommendation prioritization

### LINKED ISSUE #19: Set order/priority for therapy recommendation

### LINKED ISSUE #21: Editing moves therapy recommendation down
Editing a therapy recommendation moves it down, instead of keeping it's position in the list.

### PR DESCRIPTION
**Pull request by Unberath**
Add functionality to prioritize therapy recommendations

### CODE REVIEW

**Review by nr23730 — CHANGES_REQUESTED** [review]
This looks very good! I would suggest to apply the renaming from `Clinical data` to `Clinical data / molecular diagnostics` also in the tab next to the MTB tab as the data is also shown there.

**Comment by Unberath** [comment]
> This looks very good! I would suggest to apply the renaming from `Clinical data` to `Clinical data / molecular diagnostics` also in the tab next to the MTB tab as the data is also shown there.

I see your point but I'm hesitant renaming the entire tab as it's stock cBioPortal. I'm also not entirely happy with the naming as the heading gets quite long.

**Comment by nr23730** [comment]
> I see your point but I'm hesitant renaming the entire tab as it's stock cBioPortal. I'm also not entirely happy with the naming as the heading gets quite long.

What's the issue with that change in the stock code base? We already have changes to the core in our codebase.
How about `Clinical & molecular scores` as a shorter alterantive?

**Comment by Unberath** [comment]
> What's the issue with that change in the stock code base? We already have changes to the core in our codebase.

There is no real issue other than trying to sustain some recognizability. This tab would still have the same contents as the public version so naming it differently could be confusing?

> How about `Clinical & molecular scores` as a shorter alterantive?

From my understanding, clinical scores would mean a particular subset of clinical data. Maybe we should get feedback from the clinicians for the naming.
But I would still prefer to keep it as short as possible, this just doesn't look good imho:
image

**Comment by nr23730** [comment]
Yeah, the long title doesn't fit here.
So then my suggestion would be to merge this and change the title when we have feedback from clinicians.

**Review by nr23730 — APPROVED** [review]

**Comment by nr23730** [comment]
Fixes #19, Fixes #21

**Pull request merged**
